site_name: Portal Developer Documentation
site_url: https://pages.gitlab.io/mkdocs
site_dir: public

nav:
  - Welcome: 'index.md'
  - Guide:
    - 'overview.md'
    - 'app_json.md'
    - 'installation.md'
    - 'persisting.md'
    - 'routing_and_ac.md'
    - 'events.md'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition