site_name: Portal
site_url: https://docs.getportal.org
site_dir: public
theme:
  # name: gitbook
  # name: bootstrap
  name: material

nav:
  - Home: 'index.md'
  - Guide:
    - 'overview.md'
    - 'app_json.md'
    - 'persisting.md'
    - 'routing_and_ac.md'
    - 'peering.md'
    - 'internal_services.md'
    - 'events.md'
    - 'payment.md'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition