site_name: Portal
site_url: https://docs.getportal.org
site_dir: public
copyright: "&copy; Portal. All rights reserved."
theme:
  name: material
  logo: img/logo.svg
  favicon: img/logo.svg
  font:
    text: montserrat
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - Developer Docs:
    - 'developer_docs/overview.md'
    - 'developer_docs/existing_apps.md'
    - 'developer_docs/app_json.md'
    - 'developer_docs/persisting.md'
    - 'developer_docs/routing_and_ac.md'
    - 'developer_docs/peering.md'
    - 'developer_docs/internal_services.md'
    - 'developer_docs/events.md'
    - 'developer_docs/lifecycle.md'
    - 'developer_docs/testing.md'
    - 'developer_docs/app_template.md'
    - 'developer_docs/submitting.md'
    - 'developer_docs/revenue_share.md'
  - User Guides:
    - 'user_guides/password_management.md'
    - 'user_guides/smart_home.md'

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://getportal.org
    - icon: fontawesome/regular/envelope
      link: mailto:contact@getportal.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Portal25916803
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/get-portal
    - icon: fontawesome/brands/medium
      link: https://medium.com/getportal
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/Portal-Apps/community

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown_include.include:
      base_path: docs
