site_name: freeshard
site_url: https://docs.freeshard.net
site_dir: public
copyright: "&copy; 2024 Good For Business UG (haftungsbeschränkt)"
theme:
  name: material
  # custom_dir: overrides
  logo: img/logo.png
  favicon: img/logo.png
  font:
    text: montserrat
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Overview:
    - 'overview/index.md'
    - Concepts:
      - 'overview/concepts/single_user_isolation.md'
      - 'overview/concepts/devices.md'
      - 'overview/concepts/apps.md'
      # - 'overview/concepts/ubiquity.md'
      # - 'overview/concepts/user_interface.md'
      # - 'overview/concepts/peers.md'
  - Developer Docs:
    - 'developer_docs/overview.md'
    - 'developer_docs/docker_compose_template.md'
    - 'developer_docs/app_meta_json.md'
    - 'developer_docs/persisting.md'
    - 'developer_docs/routing_and_ac.md'
    - 'developer_docs/internal_services.md'
    - 'developer_docs/peering.md'
    - 'developer_docs/events.md'
    - 'developer_docs/lifecycle.md'
    - 'developer_docs/custom_apps.md'
    - 'developer_docs/submitting.md'
    - 'developer_docs/revenue_share.md'
    - 'developer_docs/existing_apps.md'
    # - 'developer_docs/app_template.md'
  - Blog:
      - 'blog/index.md'
  - User Guides:
      - 'user_guides/password_management.md'
      - 'user_guides/smart_home.md'

plugins:
  - blog
  - glightbox

extra:
  status:
    disabled: Feature is disabled
    upcoming: Upcoming feature
  social:
    - icon: fontawesome/solid/globe
      link: https://freeshard.net
    - icon: fontawesome/regular/envelope
      link: mailto:contact@freeshard.net
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ZXQDuTGcCf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/freeshard

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
