name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build MkDocs site for testing
        run: mkdocs build --strict --verbose --site-dir test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build MkDocs site for deployment
        run: mkdocs build --strict --verbose

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
